# Get all vaccinations from an employee
GET http://localhost:8080/employees/d6d04eb8-83e8-47bb-af10-393b457499f3/employee-vaccinations
Authorization: Bearer <JWT>

###
# Add employee vaccination
POST http://localhost:8080/employees/d6d04eb8-83e8-47bb-af10-393b457499f3/employee-vaccinations
Content-Type: application/json
Authorization: Bearer <JWT>

{
    "vaccinationCount": 1,
    "vaccinationBrand": 2
}

###
# Update employee vaccination
PUT http://localhost:8080/employees/d6d04eb8-83e8-47bb-af10-393b457499f3/employee-vaccinations/da5b5d38-ea35-4754-b9b7-b2cc2bedab8a
Content-Type: application/json
Authorization: Bearer <JWT>

{
    "vaccinationCount": 1,
    "vaccinationBrand": 1
}

###
# Delete employee vaccination by ID
DELETE http://localhost:8080/employees/4342b824-423a-4274-883e-009643ed9186/employee-vaccinations/840468c0-335b-4ade-841c-ab11211f4483
Content-Type: application/json
Authorization: Bearer <JWT>
