GET http://localhost:8080/companies

###
POST http://localhost:8080/companies
Content-Type: application/json

{
    "name": "SCIS"
}

###
POST http://localhost:8080/companies/efd12781-392b-4c97-b388-8722bd709601/departments
Content-Type: application/json

{
    "name": "SCIS Dept 1"
}

